import { Flex, Heading, Text } from "@chakra-ui/react";

export default function TermsOfUse() {
	return (
		<Flex flexDir={"column"} p={10} textAlign={"justify"} color={"#eee"}>
			<Heading my="3" size={"2xl"} id="-night-watch-terms-of-use-">
				<strong>NIGHT WATCH TERMS OF USE</strong>
			</Heading>
			<Text>
				NIGHT WATCH IS AN EXPERIMENTAL, UNIQUE, AND DEFLATIONARY ART COLLECTION
				WITH AN ON-CHAIN GAME AIMS TO TAKE THE CRYPTOART COMMUNITY TO THE NEXT
				LEVEL WITH IT&#39;S REVOLUTIONARY NEW MECHANISMS.
			</Text>
			<Text>
				THESE TERMS AND CONDITIONS (“TERMS”) RULE THE RELATIONSHIP BETWEEN NIGHT
				WATCH AND ANY PERSON (“USER”, “YOU”) ACCESSING AND/OR USING NIGHT
				WATCH’S WEBSITE (WWW.NIGHTWATCH.ART, ALSO REFERRED TO HEREIN AS
				“NIGHT WATCH WEBSITE”). PLEASE READ THESE TERMS CAREFULLY BEFORE USING
				THE NIGHT WATCH WEBSITE.
			</Text>
			<Heading
				as="h2"
				size="xl"
				my="3"
				id="-1-conditions-of-use-of-the-night-watch-website-"
			>
				<strong>1. CONDITIONS OF USE OF THE NIGHT WATCH WEBSITE</strong>
			</Heading>
			<Text>
				THE NIGHT WATCH WEBSITE IS INTENDED TO USERS WHO ARE AT LEAST EIGHTEEN
				(18) YEARS OLD. THUS, BY USING THE NIGHT WATCH WEBSITE, YOU CONFIRM THAT
				YOU ARE AT LEAST EIGHTEEN (18) YEARS OLD AND YOU ARE DEEMED TO HAVE READ
				AND ACCEPTED THESE TERMS EXHAUSTIVELY AND UNCONDITIONALLY. IF THE USER
				IS UNDER EIGHTEEN (18) YEARS OLD, THE USER UNDERTAKES TO OBTAIN THE
				PRIOR AND EXPRESS CONSENT OF HIS/HER PARENT OR LEGAL GUARDIAN TO USE THE
				NIGHT WATCH WEBSITE AND TO REVIEW THE TERMS WITH THEM. THE PARENT OR
				LEGAL GUARDIAN OF A USER UNDER EIGHTEEN (18) YEARS OLD UNDERTAKES TO
				ABIDE BY THESE TERMS AND ACKNOWLEDGES TO BE RESPONSIBLE FOR THE
				ACTIVITIES OF THE USER ON THE NIGHT WATCH WEBSITE. IN CASE OF YOUR
				DISAGREEMENT, IN WHOLE OR IN PART, WITH THESE TERMS, YOU MUST
				IMMEDIATELY CEASE ANY AND ALL USE OF THE NIGHT WATCH WEBSITE.
			</Text>
			<Heading as="h2" my="3" size="xl" id="-2-amendment-to-the-terms-">
				<strong>2. AMENDMENT TO THE TERMS</strong>
			</Heading>
			<Text>
				THE TERMS MAY BE UPDATED FROM TIME TO TIME AS NIGHT WATCH MAY DEEM
				NECESSARY OR USEFUL. IN THE EVENT YOU DO NOT AGREE TO THE TERMS,
				INCLUDING AS MAY BE AMENDED, YOU SHALL CEASE ANY AND ALL UTILIZATION OF
				THE NIGHT WATCH WEBSITE AND RELATED SERVICES.
			</Text>
			<Heading
				as="h2"
				my="3"
				size="xl"
				id="-3-access-to-the-night-watch-website-"
			>
				<strong>3. ACCESS TO THE NIGHT WATCH WEBSITE</strong>
			</Heading>
			<Text>
				YOU ARE PERSONALLY RESPONSIBLE FOR SETTING UP THE IT AND
				TELECOMMUNICATIONS RESOURCES REQUIRED TO ACCESS THE NIGHT WATCH WEBSITE
				AND USE THE SERVICES. YOU SHALL BEAR THE COST OF TELECOMMUNICATIONS WHEN
				ACCESSING THE INTERNET TO USE THE NIGHT WATCH WEBSITE. NIGHT WATCH
				RESERVES THE RIGHT TO, WITHOUT NOTICE NOR COMPENSATION, TEMPORARILY OR
				PERMANENTLY, CLOSE THE NIGHT WATCH WEBSITE OR ACCESS TO ONE OR MORE
				SERVICES IN ORDER TO PERFORM MAINTENANCE OPERATIONS. NIGHT WATCH MAY
				CARRY OUT ANY CHANGES AND IMPROVEMENTS TO THE NIGHT WATCH WEBSITE AND
				SERVICES THAT IT DEEMS NECESSARY.
			</Text>
			<Heading as="h2" my="3" size="xl" id="-4-services-">
				<strong>4. SERVICES</strong>
			</Heading>
			<Heading as="h3" my="1" size="lg" id="-4-1-general-services-">
				<strong>4.1. GENERAL SERVICES</strong>
			</Heading>
			<Text>
				THE NIGHT WATCH WEBSITE GIVES YOU ACCESS TO FUNCTIONALITIES, FEATURES
				AND SERVICES RELATED TO NIGHT WATCH NFT COLLECTIONS AND COMMUNITY (THE
				“SERVICES”). ACCESS TO SOME SERVICES MAY ONLY BE AVAILABLE TO THE HOLDER
				OF A NIGHT WATCH NFT AND REQUIRE PROOF OF OWNERSHIP BY CONNECTING A
				SUPPORTED BLOCKCHAIN-BASED DIGITAL WALLET TO THE NIGHT WATCH WEBSITE
				(“DIGITAL WALLET”). DIGITAL WALLETS ARE THIRD-PARTY PRODUCTS AND
				SERVICES THAT ARE NOT AFFILIATED, IN ANY WAY WHATSOEVER, WITH NIGHT
				WATCH NOR IN ITS CUSTODY OR CONTROL. ACCESS AND USE OF DIGITAL WALLETS
				ARE AT THE USER’S OWN RISK AND DISCRETION AND SUBJECT TO THEIR OWN
				APPLICABLE TERMS. YOU ARE SOLELY RESPONSIBLE FOR YOUR DIGITAL WALLET
				SECURITY, INCLUDING ASSOCIATED PASSWORDS, SEED WORDS, AND KEYS. NIGHT
				WATCH SHALL NOT, IN ANY EVENT WHATSOEVER, BE HELD RESPONSIBLE FOR ANY
				RISK ASSOCIATED WITH YOUR ACCESS AND/OR USE OF A DIGITAL WALLET. IN THE
				EVENT YOU LOSE OR CAN NO LONGER ACCESS YOUR DIGITAL WALLET, NIGHT WATCH
				CANNOT RETRIEVE YOUR NIGHT WATCH NFT FROM YOUR DIGITAL WALLET.
			</Text>
			<Heading
				as="h3"
				size="lg"
				id="-4-2-nft-secondary-sale-on-third-party-platform-"
			>
				<strong>4.2. NFT SECONDARY SALE ON THIRD-PARTY PLATFORM</strong>
			</Heading>
			<Text>
				USER MAY RESELL AND/OR PURCHASE NIGHT WATCH NFT ON THIRD-PARTY PLATFORMS
				AS PART OF SECONDARY SALES. PLATFORMS DEDICATED TO SECONDARY SALES ARE
				THIRD-PARTY SERVICES THAT ARE NOT AFFILIATED WITH NIGHT WATCH AND WHICH
				ACCESS AND USE ARE AT USER’S OWN RISK AND DISCRETION AND SUBJECT TO
				THEIR OWN APPLICABLE TERMS. NIGHT WATCH MAY BENEFIT FROM A PERCENTAGE OF
				THE RESALE PRICE OF YOUR NIGHT WATCH NFT, AS SET FORTH ON THE NIGHT
				WATCH WEBSITE AND SUBJECT TO THE THIRD-PARTY PLATFORM’S POLICY ON WHICH
				THE RESALE IS COMPLETED. YOU UNDERTAKE TO ONLY RESELL AND/OR PURCHASE
				NIGHT WATCH NFT ON THIRD-PARTY PLATFORMS THAT (I) CRYPTOGRAPHICALLY
				VERIFY EACH NFT OWNER’S RIGHTS TO DISPLAY AND LIST A NIGHT WATCH NFT FOR
				SALE, TO ENSURE THAT ONLY THE ACTUAL OWNER OF THIS NFT CAN PROCEED WITH
				ITS RESALE, AND (II) PROVIDE FOR A PERCENTAGE OF THE RESALE PRICE TO BE
				AUTOMATICALLY GRANTED TO NIGHT WATCH UPON RESALE. BY RESELLING AND/OR
				PURCHASING A NIGHT WATCH NFT ON AN AUTHORIZED THIRD-PARTY PLATFORM, YOU
				AGREE TO ABIDE BY THESE TERMS.
			</Text>
			<Heading as="h2" my="3" size="xl" id="-5-undertakings-of-the-parties-">
				<strong>5. UNDERTAKINGS OF THE PARTIES</strong>
			</Heading>
			<Heading as="h3" my="1" size="lg" id="-5-1-users-undertakings-">
				<strong>5.1. USERS UNDERTAKINGS</strong>
			</Heading>
			<Text>
				USERS SHALL NOT, DIRECTLY OR INDIRECTLY, WITHOUT BEING EXPRESSLY
				AUTHORIZED BY THESE TERMS AND/OR THE DIGITAL OWNERSHIP ASSIGNMENT, OR BY
				PRIOR WRITTEN CONSENT OF NIGHT WATCH, IN ANY WAY WHATSOEVER: (I) COPY,
				MODIFY, COMMUNICATE, TRANSMIT OR CREATE ANY DERIVATIVE WORK, USE,
				COMMERCIALIZE OR REPRODUCE ALL OR PART OF THE NIGHT WATCH WEBSITE AND/OR
				NIGHT WATCH PROPERTY, AND RELATED INTELLECTUAL PROPERTY RIGHTS OF NIGHT
				WATCH, OR REGISTER OR ATTEMPT TO REGISTER ANY TRADEMARK OR COPYRIGHT OR
				OTHERWISE ACQUIRE ADDITIONAL INTELLECTUAL PROPERTY RIGHTS IN OR TO ANY
				NIGHT WATCH PROPERTY; USE THE NIGHT WATCH WEBSITE OR ANY NIGHT WATCH
				PROPERTY TO CREATE, ENDORSE, SUPPORT, PROMOTE OR CONDONE ANY CONTENT,
				MATERIAL OR SPEECH THAT IS, OR MAY BE DEEMED TO BE BY NIGHT WATCH AT ITS
				SOLE DISCRETION, DEFAMATORY, OBSCENE, PORNOGRAPHIC, INDECENT, ABUSIVE,
				OFFENSIVE, HARASSING, VIOLENT, HATEFUL, RACIST, DISCRIMINATORY,
				INFLAMMATORY OR OTHERWISE OBJECTIONABLE OR INAPPROPRIATE; AND, IN
				GENERAL, ACCESS, DOWNLOAD, UPLOAD, SHARE, COMMUNICATE ANY CONTENT AND/OR
				USE THE NIGHT WATCH WEBSITE OR NIGHT WATCH PROPERTY IN A WAY THAT MAY
				INFRINGE THE RIGHTS, INCLUDING INTELLECTUAL PROPERTY RIGHTS, OF NIGHT
				WATCH OR THIRD PARTIES, DAMAGE THE REPUTATION, RIGHTS AND INTERESTS OF
				NIGHT WATCH, OR FALSELY SUGGEST AN AFFILIATION WITH OR ENDORSEMENT BY
				NIGHT WATCH. AND, IN GENERAL, VIOLATE ANY LAW OR REGULATION, OR MAKE ANY
				USE OF THE NIGHT WATCH WEBSITE, SERVICES OR NIGHT WATCH PROPERTY THAT
				MAY BE DEEMED CONTRARY TO PUBLIC ORDER OR UNFAIR.
			</Text>
			<Heading as="h3" my="1" size="lg" id="-5-2-undertakings-of-night-watch-">
				<strong>5.2. UNDERTAKINGS OF NIGHT WATCH</strong>
			</Heading>
			<Text>
				NIGHT WATCH ENDEAVORS USE REASONABLE EFFORTS TO (I) ACT HONESTLY, FAIRLY
				AND PROFESSIONALLY, (II) COMMUNICATE WITH THE HOLDERS OF NIGHT WATCH NFT
				IN A FAIR AND CLEAR MANNER, (III) PREVENT, IDENTIFY, MANAGE AND DISCLOSE
				ANY CONFLICTS OF INTEREST THAT MAY ARISE, (IV) MAINTAIN ALL OF ITS
				SYSTEMS AND SECURITY ACCESS PROTOCOLS TO APPROPRIATE STANDARDS OF
				APPLICABLE LAWS AND REGULATIONS, AND, IN GENERAL (V) ACT IN THE BEST
				INTERESTS OF THE HOLDERS OF NIGHT WATCH NFT AND TREAT THEM EQUALLY,
				UNLESS PROVIDED OTHERWISE ON THE NIGHT WATCH WEBSITE OR ANY OTHER NOTICE
				BY NIGHT WATCH.
			</Text>
			<Heading as="h2" my="3" size="xl" id="-6-security-">
				<strong>6. SECURITY</strong>
			</Heading>
			<Heading as="h3" my="1" size="lg" id="-6-1-night-watch-website-security-">
				<strong>6.1. NIGHT WATCH WEBSITE SECURITY</strong>
			</Heading>
			<Text>
				NIGHT WATCH SHALL MAKE ITS BEST EFFORTS TO DEPLOY THE NECESSARY
				RESOURCES TO ENSURE USERS’ ACCESS TO AND EFFECTIVE OPERATION OF THE
				NIGHT WATCH WEBSITE TWENTY-FOUR HOURS A DAY AND SEVEN DAYS A WEEK.
				HOWEVER, GIVEN THE LIMITATIONS RELATED TO THE INTERNET, NIGHT WATCH
				CANNOT GUARANTEE THAT ACCESS AND OPERATION OF THE NIGHT WATCH WEBSITE
				WILL NOT BE INTERRUPTED, SUCH AS IN EVENT OF FORCE MAJEURE, MALFUNCTION
				OF THE USERS’ EQUIPMENT, MALFUNCTIONS OF THE USERS’ INTERNET NETWORKS
				AND/OR MAINTENANCE OPERATIONS DESIGNED TO IMPROVE THE NIGHT WATCH
				WEBSITE. THE USER HEREBY REPRESENTS, WARRANTS, AND AGREES THAT, WHEN
				ACCESSING AND/OR USING THE NIGHT WATCH WEBSITE AND SERVICES, THE USER
				SHALL REFRAIN FROM ANY ACT AND/OR OMISSION WHICH COULD, IN ANY WAY
				WHATSOEVER (I) JEOPARDIZE THE SECURITY OF THE NIGHT WATCH WEBSITE; (II)
				ATTEMPT, IN ANY MANNER, TO OBTAIN PASSWORDS OR OTHER SECURITY
				INFORMATION FROM ANY OTHER USER; (III) VIOLATE THE SECURITY OF ANY
				COMPUTER NETWORK, OR CRACKS ANY PASSWORDS OR SECURITY ENCRYPTION CODES;
				(IV) RUN ANY PROCESSES THAT INTERFERE WITH THE PROPER WORKING OF THE
				NIGHT WATCH WEBSITE AND SERVICES; (V) DISTURB, HINDER AND/OR PREVENT THE
				PROPER FUNCTIONING OF THE NIGHT WATCH WEBSITE AND SERVICES (SUCH AS, BUT
				NOT LIMITED TO, DOWNLOADING VIRUSES OR MALICIOUS CODE WHATSOEVER OR BY
				PERFORMING HACKING ACTIVITIES OF ANY NATURE OR THAT OTHERWISE INTERFERE
				WITH THE PROPER FUNCTIONING OF THE NIGHT WATCH WEBSITE AND SERVICES).
			</Text>
			<Heading as="h3" my="1" size="lg" id="-6-2-malicious-third-parties-">
				<strong>6.2. MALICIOUS THIRD PARTIES</strong>
			</Heading>
			<Text>
				PLEASE BE AWARE THAT MALICIOUS THIRD PARTIES MAY OFFER FOR SALE NFT
				COUNTERFEITED NIGHT WATCH PROPERTY AND/OR FALSELY ACT AS AFFILIATED TO
				OR ENDORSED BY NIGHT WATCH. IN CASE OF DOUBT, PLEASE CONTACT NIGHT WATCH
				IN ACCORDANCE WITH ARTICLE 12 BELOW. YOUR INTERACTIONS WITH THESE THIRD
				PARTIES ARE AT YOUR OWN RISKS AND DISCRETION. NIGHT WATCH IS NOT
				RESPONSIBLE, IN ANY WAY WHATSOEVER, FOR ANY ACT OR OMISSION OF SAID
				MALICIOUS THIRD PARTIES, NOR ANY ADVERSE CONSEQUENCE RESULTING FROM YOUR
				INTERACTIONS WITH THEM.
			</Text>
			<Heading as="h2" my="3" size="xl" id="-7-disclaimer-">
				<strong>7. DISCLAIMER</strong>
			</Heading>
			<Text>
				NIGHT WATCH OFFERS SERVICES RELATED TO CRYPTO-ASSETS (NFT) THAT ARE
				UNIQUE AND NOT FUNGIBLE WITH OTHER CRYPTO-ASSETS. EACH NIGHT WATCH NFT
				IS UNIQUE AND EXCLUSIVE TO ITS OWNER. NIGHT WATCH IS NOT A PROVIDER OF
				DIGITAL ASSET SERVICES INCLUDING, BUT NOT LIMITED TO, SERVICES REGARDING
				INITIAL COIN OFFERING; CUSTODY OF DIGITAL ASSETS ON BEHALF OF THIRD
				PARTIES OR ACCESS TO DIGITAL ASSETS FOR THE PURPOSE OF HOLDING, STORING
				AND TRANSFERRING DIGITAL ASSETS; THE PURCHASE AND SALE OF DIGITAL ASSETS
				IN LEGAL TENDER; THE EXCHANGE OF DIGITAL ASSETS FOR OTHER DIGITAL
				ASSETS; THE OPERATION OF A DIGITAL ASSET TRADING PLATFORM; OR ANY
				SERVICES RELATED TO THIRD PARTY ORDER RECEPTION AND TRANSMISSION, THIRD
				PARTY PORTFOLIO MANAGEMENT, ADVICE, UNDERWRITING, GUARANTEED PLACEMENT
				AND UNGUARANTEED PLACEMENT. NIGHT WATCH DOES NOT PROVIDE ASSET
				INTERMEDIATION SERVICES INCLUDING, BUT NOT LIMITED TO, SERVICES RELATED
				TO THE OFFER, TO CLIENTS OR POTENTIAL CLIENTS, TO ACQUIRE RIGHTS ON ONE
				OR MORE ASSETS ON THE BASIS OF THE POSSIBILITY OF A DIRECT OR INDIRECT
				FINANCIAL RETURN OR SIMILAR ECONOMIC EFFECT. IN THIS REGARD, THE USER
				HEREBY REPRESENTS, WARRANTS, AND AGREES THAT ANY USE OF THE NIGHT WATCH
				WEBSITE AND SERVICES, INCLUDING ANY PURCHASE OF A NIGHT WATCH NFT, IS
				MADE FOR ITS SOLE PERSONAL COLLECTION, USE AND ENJOYMENT. USER SHALL
				REFRAIN FROM ANY ACT AND/OR OMISSION WHICH COULD, IN ANY WAY WHATSOEVER,
				BE INTERPRETED AS OR SUGGEST THAT (I) THE USER IS ACCESSING OR USING THE
				NIGHT WATCH WEBSITE AND/OR SERVICES, INCLUDING PURCHASING A NIGHT WATCH
				NFT, FOR SPECULATIVE OR INVESTMENT PURPOSES, FOR USE AS A SUBSTITUTE FOR
				CURRENCY OR OTHER MEDIUM OF EXCHANGE, OR FOR RESALE OR REDISTRIBUTION,
				OR THAT (II) ACCESSING OR USING THE NIGHT WATCH WEBSITE AND/OR SERVICES,
				INCLUDING PURCHASING A NIGHT WATCH NFT, MAY CONSTITUTE AN OPPORTUNITY TO
				GAIN ECONOMIC BENEFIT OR PROFIT, OR AN INVESTMENT, EQUITY, OR OTHER
				OWNERSHIP OR PROFIT-SHARING INTEREST IN NIGHT WATCH OR ITS AFFILIATES OR
				BUSINESS PARTNERS OF ANY KIND. IN THIS REGARD, NIGHT WATCH MAKES NO
				WARRANTIES WHATSOEVER WITH REGARD TO ANY FUTURE VALUE OR RESALE PRICE OF
				A NIGHT WATCH NFT. YOU ARE THE SOLE RESPONSIBLE FOR YOUR COMPLIANCE WITH
				APPLICABLE LAWS AND REGULATIONS, INCLUDING TAX OBLIGATIONS IN RELATION
				WITH NFT AND CRYPTOCURRENCIES. PLEASE BE AWARE THAT CHANGES IN
				APPLICABLE LAWS AND REGULATIONS MAY IMPACT THE SERVICES AND YOUR RIGHTS
				AND OBLIGATIONS REGARDING YOUR NIGHT WATCH NFT.
			</Text>
			<Heading as="h2" my="3" size="xl" id="-8-warranty-and-liability-">
				<strong>8. WARRANTY AND LIABILITY</strong>
			</Heading>
			<Heading as="h3" my="1" size="lg" id="-8-1-warranties-">
				<strong>8.1. WARRANTIES</strong>
			</Heading>
			<Text>
				IT IS EXPRESSLY AGREED THAT NIGHT WATCH OBLIGATIONS UNDER THESE TERMS
				ARE OBLIGATIONS OF MEANS. TO THE GREATEST EXTENT PERMITTED BY APPLICABLE
				LAW, THE USER EXPRESSLY ACKNOWLEDGES THAT THE NIGHT WATCH WEBSITE,
				SERVICES, INCLUDING NIGHT WATCH NFT, ARE PROVIDED BY NIGHT WATCH “AS
				IS”. OTHER THAN AS PROVIDED IN THESE TERMS AND TO THE FULLEST EXTENT
				PERMISSIBLE BY APPLICABLE LAW, NIGHT WATCH MAKES NO OTHER WARRANTIES OR
				REPRESENTATIONS, EXPRESS OR IMPLIED, AND HEREBY DISCLAIMS ALL IMPLIED
				WARRANTIES. NIGHT WATCH MAKES NO WARRANTIES WHATSOEVER, REGARDING THE
				NIGHT WATCH WEBSITE, THE SERVICES, AND ANY TRANSACTION INVOLVING, IN
				WHOLE OR IN PART, NIGHT WATCH NFT AND/OR CRYPTOCURRENCIES, INCLUDING,
				BUT NOT LIMITED TO, WITH REGARD TO ANY RISK ASSOCIATED WITH NIGHT WATCH
				NFT, SUCH AS, RISK OF FAILURE TO TRANSFER THE NFT TO THE USER DUE TO AN
				ERROR, SUCH AS FORGOTTEN PASSWORDS, MISTYPED ADDRESSES OR INCORRECTLY
				CONSTRUCTED TRANSACTIONS, MINING ATTACKS, CYBERSECURITY ATTACKS,
				BLOCKCHAIN MALFUNCTIONS OR OTHER TECHNICAL ERRORS, TELECOMMUNICATIONS
				FAILURE, UNFAVORABLE REGULATORY DETERMINATIONS OR ACTIONS IN ONE OR MORE
				JURISDICTIONS (INCLUDING WITH RESPECT TO NFTS AND/OR CRYPTOCURRENCIES),
				TAXATION OF NFTS OR CRYPTOCURRENCIES, PERSONAL INFORMATION DISCLOSURE,
				UNINSURED LOSSES, UNANTICIPATED RISKS, VOLATILITY RISKS, SERVER FAILURE
				OR DATA LOSS, CORRUPTED OR OTHERWISE INACCESSIBLE DIGITAL WALLETS,
				UNAUTHORIZED ACCESS, INABILITY TO ACCESS, TRANSFER OR DISPLAY THE NFT,
				RISKS ARISING FROM THIRD-PARTY PROVIDERS, INCLUDING THIRD-PARTY
				PROVIDERS THAT MAY MINT AND/OR STORE THE NFT, AND ANY DAMAGES ARISING
				FROM ANY UNAUTHORIZED THIRD-PARTY ACTIVITIES, INCLUDING WITHOUT
				LIMITATION THE INTRODUCTION OF VIRUSES OR OTHER MALICIOUS CODE, PHISHING
				ATTACKS, SYBIL ATTACKS, FIFTY-ONE PERCENT (51%) ATTACKS, BRUTE FORCING
				CHANGES TO THE PROTOCOL RULES OF THE BLOCKCHAIN (I.E., “FORKS”), OR
				OTHER MEANS OF ATTACK THAT MAY AFFECT, IN ANY WAY, THE NFT. NIGHT WATCH
				DOES NOT WARRANT THAT THE USER’S ACCESS AND USE OF THE NIGHT WATCH
				WEBSITE AND THE SERVICES WILL BE UNINTERRUPTED, TIMELY AND FREE FROM
				ERRORS, MALFUNCTIONS, VIRUSES AND MALICIOUS CODES OF ANY KIND
				WHATSOEVER. NO INFORMATION PROVIDED ON THE NIGHT WATCH WEBSITE IS EVER
				GUARANTEED IN ANY WAY WHATSOEVER. THE USER EXPRESSLY ACKNOWLEDGES AND
				ACCEPTS THAT ELECTRONIC COMMUNICATIONS MAY NOT BE FREE FROM
				INTERFERENCES WITH THIRD PARTIES. NIGHT WATCH SHALL IN NO EVENT BE
				LIABLE FOR ANY DAMAGES, LOSSES, COSTS, EXPENSES AND LOSS OF PROFIT, OF
				WHATEVER NATURE AND KIND, RESULTING FROM OR ARISING OUT OF SUCH
				INTERFERENCE WITH THIRD PARTIES THROUGH THE INTERNET NETWORK.
			</Text>
			<Heading as="h3" my="1" size="lg" id="-8-2-indemnification-">
				<strong>8.2. INDEMNIFICATION</strong>
			</Heading>
			<Text>
				THE USER SHALL INDEMNIFY, DEFEND AND HOLD NIGHT WATCH, AND ITS MEMBER,
				DIRECTORS, OFFICERS, EMPLOYEES, AND AGENTS (COLLECTIVELY, &quot;THE
				NIGHT WATCH CLAIMANTS&quot;) HARMLESS FROM AND AGAINST ANY AND ALL
				CLAIMS, LIABILITIES, JUDGMENTS, AWARDS, LOSSES, DAMAGES, COSTS AND
				EXPENSES (INCLUDING, BUT NOT LIMITED TO, REASONABLE ATTORNEYS&#39;
				FEES), ARISING OUT FROM (I) ANY BREACH BY THE USER, OR ANY OF ITS
				RESPECTIVE EMPLOYEES OR AGENTS IF ANY, OF THIS TERMS OR OF ANY WARRANTY,
				REPRESENTATION, COVENANT OR OBLIGATION CONTAINED HEREIN; (II) ANY
				INFRINGEMENT OR ALLEGED INFRINGEMENT ON THE PART OF THE NIGHT WATCH
				CLAIMANTS IN CONNECTION WITH ANY AND ALL USE OF THE NIGHT WATCH WEBSITE,
				SERVICES AND/OR NIGHT WATCH NFT BY THE USER.
			</Text>
			<Heading as="h3" my="1" size="lg" id="-8-3-limitation-of-liability-">
				<strong>8.3. LIMITATION OF LIABILITY</strong>
			</Heading>
			<Text>
				TO THE GREATEST EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT SHALL
				NIGHT WATCH BE LIABLE FOR ANY INDIRECT DAMAGES CAUSED TO A USER IN
				RELATION TO ACCESS AND/OR USE OF THE NIGHT WATCH WEBSITE AND/OR THE
				SERVICES.
			</Text>
			<Heading
				as="h2"
				my="3"
				size="xl"
				id="-9-ownership-of-intellectual-properties-"
			>
				<strong>9. OWNERSHIP OF INTELLECTUAL PROPERTIES</strong>
			</Heading>
			<Text>
				OWNERSHIP OF ALL BANNERS, LOGOS, NFT ARTWORKS, AND ANY OTHER VISUAL
				MATERIAL RELATED TO NIGHT WATCH EXCLUSIVELY BELONGS TO THE NIGHT WATCH
				TEAM. ANY USAGE OF SUCH VISUAL MATERIAL WITHOUT THE EXPRESS PERMISSION
				OF NIGHT WATCH TEAM IS STRICTLY PROHIBITED.
			</Text>
			<Heading
				as="h2"
				size="xl"
				id="-10-right-to-modify-the-prices-of-the-products-"
				my="3"
			>
				<strong>10. RIGHT TO MODIFY THE PRICES OF THE PRODUCTS</strong>
			</Heading>
			<Text>
				THE NIGHT WATCH TEAM RESERVES THE RIGHT TO MODIFY THE PRICES OF THEIR
				PRODUCTS AT ANY TIME WITHOUT PRIOR NOTICE TO THE USER. BY ACCESSING AND
				USING THE NIGHT WATCH PRODUCTS AND SERVICES, THE USER ACCEPTS AND AGREES
				TO THESE POTENTIAL PRICE CHANGES.
			</Text>
			<Heading
				as="h2"
				size="xl"
				id="-11-right-to-modify-artwork-in-nfts-and-other-material-"
				my="3"
			>
				<strong>11. RIGHT TO MODIFY ARTWORK IN NFTS AND OTHER MATERIAL</strong>
			</Heading>
			<Text>
				THE NIGHT WATCH TEAM RESERVES THE RIGHT TO MODIFY THE ARTWORK, INCLUDING
				BUT NOT LIMITED TO THE NFTS, BANNERS, WEBSITE DESIGN, AND ANY OTHER
				MATERIAL, AT ANY TIME WITHOUT PRIOR NOTICE TO THE USER. THE USER
				ACKNOWLEDGES AND ACCEPTS THAT THE NIGHT WATCH TEAM HAS THE SOLE
				DISCRETION TO MODIFY SUCH ARTWORK AND MATERIAL AND THAT ANY SUCH
				MODIFICATIONS WILL NOT AFFECT THE AUTHENTICITY OR OWNERSHIP OF ANY NFTS
				ALREADY OWNED BY THE USER.
			</Text>
			<Heading as="h2" my="3" size="xl" id="-12-no-return-policy-clause-">
				<strong>12. NO RETURN POLICY CLAUSE</strong>
			</Heading>
			<Text>
				NIGHT WATCH DOES NOT OFFER ANY RETURN POLICY. ALL SALES ARE FINAL, AND
				USERS ARE ADVISED TO CAREFULLY REVIEW THEIR PURCHASES BEFORE MAKING A
				TRANSACTION. BY PURCHASING ANY PRODUCT OR SERVICE FROM NIGHT WATCH, THE
				USER ACKNOWLEDGES AND ACCEPTS THIS NO RETURN POLICY CLAUSE.
			</Text>
			<Heading as="h2" my="3" size="xl" id="-13-miscellaneous-">
				<strong>13. MISCELLANEOUS</strong>
			</Heading>
			<Heading as="h3" my="1" size="lg" id="-13-1-breach-of-terms-">
				<strong>13.1. BREACH OF TERMS</strong>
			</Heading>
			<Text>
				IF THE USER’S UTILIZATION OF THE NIGHT WATCH WEBSITE IS DEEMED IN BREACH
				OF THE TERMS, NIGHT WATCH RESERVES THE RIGHT TO LIMIT, SUSPEND OR
				TERMINATE, TEMPORARILY OR PERMANENTLY, AS OF RIGHT, WITHOUT ANY
				INDEMNIFICATION, COMPENSATION OR REFUND WHATSOEVER BEING OWED AND
				WITHOUT ANY PREJUDICE TO ANY LEGAL ACTION THAT NIGHT WATCH MAY BE
				ENTITLED TO, THE USER’S ACCESS TO THE NIGHT WATCH WEBSITE AND/OR THE
				SERVICES AVAILABLE TO THE USER. NIGHT WATCH SHALL INFORM THE USER OF ITS
				DECISION TO SUSPEND OR LIMIT THE USER’S RIGHTS AND MAY, AT ITS
				DISCRETION, DECIDE TO RESTORE THE USER’S RIGHTS.
			</Text>
			<Heading as="h3" my="1" size="lg" id="-13-2-third-party-content-">
				<strong>13.2. THIRD PARTY CONTENT</strong>
			</Heading>
			<Text>
				THE NIGHT WATCH WEBSITE MAY DISPLAY HYPERTEXT LINKS REDIRECTING THE USER
				TO THIRD PARTY WEBSITES AND/OR APPLICATIONS. NIGHT WATCH SHALL NOT BE
				HELD LIABLE, IN ANY WAY WHATSOEVER, IN RESPECT OF ANY HYPERTEXT LINKS TO
				THIRD PARTIES THAT MAY BE ACCESSIBLE ON THE NIGHT WATCH WEBSITE. IN THIS
				RESPECT, PLEASE NOTE THAT NIGHT WATCH NEITHER HAS ANY CONTROL OVER THE
				CONTENT PUBLISHED BY SUCH THIRD PARTIES NOR MONITORS SUCH CONTENT. AS A
				RESULT, NIGHT WATCH SHALL IN NO EVENT BE HELD LIABLE IN RESPECT OF ANY
				CONTENT PUBLISHED BY THIRD PARTIES WHATSOEVER. THE USER IS HEREBY
				INVITED TO DULY READ THE TERMS AND CONDITIONS GOVERNING THIRD-PARTY
				WEBSITES AND APPLICATIONS THAT THE USER MAY ACCESS BY CLICKING ON
				HYPERTEXT LINKS DISPLAYED ON THE NIGHT WATCH WEBSITE AND RELATED WEBSITE
				PAGES. IN THE EVENT THAT ANY CONTENT POSTED ON THE NIGHT WATCH WEBSITE
				DOES NOT COMPLY WITH THESE TERMS AND/OR INFRINGES APPLICABLE LEGAL AND
				REGULATORY PROVISIONS, IN PARTICULAR BECAUSE IT CONSTITUTES MANIFESTLY
				UNLAWFUL CONTENT (E.G., DEFAMATORY, DENIGRATING OR INFRINGING ON THE
				USER&#39;S INTELLECTUAL PROPERTY RIGHTS), ANY USER MAY REPORT SUCH
				INFRINGEMENT BY CONTACTING NIGHT WATCH IN ACCORDANCE WITH ARTICLE 12.
			</Text>
			<Heading as="h3" my="1" size="lg" id="-13-3-assignment-">
				<strong>13.3. ASSIGNMENT</strong>
			</Heading>
			<Text>
				NIGHT WATCH MAY TRANSFER ALL OR PART OF ITS RIGHTS AND OBLIGATIONS UNDER
				THESE TERMS TO ANY ENTITY, AFFILIATE, SUBSIDIARY OR THIRD-PARTY,
				INCLUDING, BUT NOT LIMITED TO, IN CASE OF MERGER, DIVISION, PARTIAL
				ASSET TRANSFER OR FULL OR PARTIAL BUSINESS DISPOSAL. THE USER SHALL NOT
				TRANSFER ALL OR PART OF ITS OBLIGATIONS UNDER THESE TERMS, IN ANY WAY
				WHATSOEVER, WITHOUT THE EXPRESS PRIOR WRITTEN AGREEMENT OF NIGHT WATCH.
			</Text>
			<Heading as="h3" my="1" size="lg" id="-13-4-validity-">
				<strong>13.4. VALIDITY</strong>
			</Heading>
			<Text>
				IN THE EVENT ANY ONE OR MORE OF THE PROVISIONS OF THESE TERMS ARE
				UNENFORCEABLE, IT SHALL BE STRICKEN FROM THE APPLICABLE DOCUMENT, BUT
				THE REMAINDER OF THE TERMS SHALL REMAIN IN FORCE. THE PROVISIONS
				DECLARED UNENFORCEABLE SHALL BE REPLACED BY THE PROVISIONS THAT ARE
				CLOSEST IN MEANING AND SCOPE TO THE INITIAL PROVISIONS.
			</Text>
			<Heading as="h3" my="1" size="lg" id="-13-5-electronic-communication-">
				<strong>13.5. ELECTRONIC COMMUNICATION</strong>
			</Heading>
			<Text>
				IN ACCORDANCE WITH APPLICABLE LAW, THE USER ACKNOWLEDGES AND AGREES THAT
				INFORMATION EXCHANGED BETWEEN THE USER AND NIGHT WATCH IN ELECTRONIC
				FORMAT (INCLUDING VIA EMAIL) SHALL BE DEEMED VALID MEANS OF
				COMMUNICATION., NOTICE AND PROOF, EQUIVALENT TO INFORMATION IN PAPER
				FORMAT.
			</Text>
			<Heading as="h2" my="3" size="xl" id="-14-contact-information-">
				<strong>14. CONTACT INFORMATION</strong>
			</Heading>
			<Text>CONTACT US BY E-MAIL AT NIGHTWATCHWALKS@GMAIL.COM</Text>
			<Heading
				as="h2"
				my="3"
				size="xl"
				id="-15-digital-millennium-copyright-act-"
			>
				<strong>15. DIGITAL MILLENNIUM COPYRIGHT ACT</strong>
			</Heading>
			<Text>
				NOTICE. WE RESPECT THE INTELLECTUAL PROPERTY RIGHTS OF OTHERS AND WE ASK
				YOU TO DO THE SAME. IF YOU ARE A COPYRIGHT OWNER OR AN AGENT OF A
				COPYRIGHT OWNER AND BELIEVE THAT ANY CONTENT ON THE SERVICES INFRINGES
				UPON YOUR COPYRIGHTS (OTHER THAN CONTENT THAT WAS PREVIOUSLY UPLOADED BY
				YOU TO NIGHT WATCH AND AS TO WHICH THE USER-TO-USER COMPLAINT PROCESS
				APPLIES AS DESCRIBED BELOW), YOU MAY SUBMIT A NOTIFICATION PURSUANT TO
				THE DIGITAL MILLENNIUM COPYRIGHT ACT (&quot;DMCA&quot;) BY CONTACTING US
				AT NIGHTWATCHWALKS@GMAIL.COM OR TO THE ADDRESS PROVIDED IN ARTICLE 12,
				ATTENTION DMCA AGENT. IF A COPYRIGHT OWNER IS UNDER THE AGE OF 13, A
				DMCA NOTICE MUST BE SUBMITTED BY A PARENT OR OTHER REPRESENTATIVE OF THE
				RIGHTSHOLDER, RATHER THAN DIRECTLY BY AN UNDER-13 USER. YOU ACKNOWLEDGE
				THAT IF YOU FAIL TO COMPLY WITH ALL OF THE REQUIREMENTS OF THIS SECTION
				5(A), YOUR DMCA NOTICE MAY NOT BE VALID. YOU MUST PROVIDE THE FOLLOWING
				INFORMATION IN WRITING (SEE 17 U.S.C 512(C)(3) FOR FURTHER DETAIL): AN
				ELECTRONIC OR PHYSICAL SIGNATURE OF THE PERSON AUTHORIZED TO ACT ON
				BEHALF OF THE OWNER OF THE COPYRIGHT OR OTHER RIGHT BEING INFRINGED; A
				DESCRIPTION OF THE COPYRIGHT-PROTECTED WORK OR OTHER INTELLECTUAL
				PROPERTY RIGHT THAT YOU CLAIM HAS BEEN INFRINGED; A DESCRIPTION OF THE
				MATERIAL THAT YOU CLAIM IS INFRINGING AND WHERE IT IS LOCATED; YOUR
				ADDRESS, TELEPHONE NUMBER, AND EMAIL ADDRESS; A STATEMENT BY YOU THAT
				YOU HAVE A GOOD FAITH BELIEF THAT THE USE OF THOSE MATERIALS IS NOT
				AUTHORIZED BY THE COPYRIGHT OWNER, ITS AGENT, OR THE LAW; AND A
				STATEMENT BY YOU THAT THE ABOVE INFORMATION IN YOUR NOTICE IS ACCURATE
				AND THAT, UNDER PENALTY OF PERJURY, YOU ARE THE COPYRIGHT OR
				INTELLECTUAL PROPERTY OWNER OR AUTHORIZED TO ACT ON THE COPYRIGHT OR
				INTELLECTUAL PROPERTY OWNER’S BEHALF. COUNTER-NOTICE. REGARDING ANY
				CONTENT THAT WAS REMOVED OR DISABLED, IF YOU BELIEVE THAT YOUR CONTENT
				IS NOT INFRINGING OR THAT YOU HAVE THE AUTHORIZATION FROM THE COPYRIGHT
				OWNER, THE COPYRIGHT OWNER’S AGENT, OR PURSUANT TO THE LAW, TO POST AND
				USE THE MATERIAL IN YOUR CONTENT, YOU MAY SEND A COUNTER-NOTICE TO OUR
				COPYRIGHT AGENT. ANY COUNTER-NOTICE SUBMITTED ON BEHALF OF AN UNDER-13
				USER MUST BE SUBMITTED BY A PARENT OR OTHER ADULT REPRESENTATIVE. WHEN
				OUR COPYRIGHT AGENT RECEIVES A COUNTER-NOTICE, WE MAY SEND A COPY OF THE
				COUNTER-NOTICE TO THE ORIGINAL COMPLAINING PARTY INFORMING THAT PARTY
				THAT WE MAY, IN 10 BUSINESS DAYS, REPLACE THE REMOVED CONTENT OR STOP
				DISABLING IT. UNLESS THE COPYRIGHT OWNER FILES AN ACTION SEEKING A COURT
				ORDER AGAINST THE PROVIDER OF THE CONTENT, THE REMOVED CONTENT MAY BE
				REPLACED OR ACCESS TO IT RESTORED, IN 10 TO 14 BUSINESS DAYS OR MORE
				AFTER RECEIPT OF THE COUNTER-NOTICE, IN NIGHT WATCH’ SOLE DISCRETION.
				REPEAT INFRINGER POLICY. NIGHT WATCH’ INTELLECTUAL PROPERTY POLICY IS
				TO: (I) REMOVE OR DISABLE ACCESS TO MATERIAL THAT NIGHT WATCH KNOWS TO
				BE INFRINGING THE INTELLECTUAL PROPERTY RIGHTS OF THIRD PARTIES OR THAT
				HAS BEEN IDENTIFIED IN A VALID DMCA NOTICE SUBMITTED BY AN INTELLECTUAL
				PROPERTY RIGHTS OWNER OR HIS OR HER AGENT; AND (II) IN APPROPRIATE
				CIRCUMSTANCES, TO TERMINATE THE ACCOUNT OF AND BLOCK ACCESS TO THE NIGHT
				WATCH WEBSITE AND SERVICES BY ANY USER WHO REPEATEDLY OR EGREGIOUSLY
				INFRINGES OTHER PEOPLE’S COPYRIGHTS OR OTHER INTELLECTUAL PROPERTY
				RIGHTS. TRADEMARK INFRINGEMENT OUR POLICIES PROHIBIT A USER FROM
				PROVIDING USER-GENERATED CONTENT THAT INFRINGES TRADEMARKS. IF A USER
				PROVIDES CONTENT THAT INFRINGES TRADEMARKS, THE USER’S CONTENT CAN BE
				BLOCKED OR REMOVED. IF YOU ARE A TRADEMARK OWNER THAT BELIEVES YOUR
				TRADEMARK IS BEING INFRINGED, PLEASE NOTE THAT WE ARE NOT IN A POSITION
				TO MEDIATE DISPUTES BETWEEN USERS AND THE HOLDERS OF TRADEMARK RIGHTS.
				THAT BEING SAID, WE TAKE YOUR RIGHTS SERIOUSLY. SO, WE WILL LOOK INTO
				AND TRY TO RESOLVE ANY ALLEGATIONS OF TRADEMARK INFRINGEMENT. THEREFORE,
				IF YOU FEEL THAT YOUR TRADEMARK RIGHTS ARE BEING INFRINGED, CONTACT US
				AT NIGHTWATCHWALKS@GMAIL.COM OR AT THE ADDRESS PROVIDED IN ARTICLE 12,
				ATTENTION TRADEMARK AGENT. WHEN YOU CONTACT US, PLEASE PROVIDE THE
				FOLLOWING INFORMATION IN WRITING: AN ELECTRONIC OR PHYSICAL SIGNATURE OF
				THE PERSON AUTHORIZED TO ACT ON BEHALF OF THE OWNER OF THE TRADEMARK; A
				DESCRIPTION OF THE TRADEMARK RIGHT THAT YOU CLAIM HAS BEEN INFRINGED; A
				DESCRIPTION OF THE MATERIAL THAT YOU CLAIM IS INFRINGING AND WHERE IT IS
				LOCATED; YOUR ADDRESS, TELEPHONE NUMBER, AND EMAIL ADDRESS; A STATEMENT
				BY YOU THAT YOU HAVE A GOOD FAITH BELIEF THAT THE USE OF THOSE MATERIALS
				IS NOT AUTHORIZED BY THE TRADEMARK OWNER, ITS AGENT, OR THE LAW; AND A
				STATEMENT BY YOU THAT THE ABOVE INFORMATION IN YOUR NOTICE IS ACCURATE
				AND THAT, UNDER PENALTY OF PERJURY, YOU ARE THE TRADEMARK OWNER OR
				AUTHORIZED TO ACT ON THE COPYRIGHT OR INTELLECTUAL PROPERTY OWNER’S
				BEHALF.
			</Text>
			<Heading as="h2" my="3" size="xl" id="-16-applicable-law-">
				<strong>16. APPLICABLE LAW</strong>
			</Heading>
			<Text>
				THE VALIDITY OF THESE TERMS AND ANY OF ITS TERMS AND PROVISIONS, AS WELL
				AS THE RIGHTS AND DUTIES OF THE PARTIES HEREUNDER, SHALL BE GOVERNED,
				INTERPRETED AND ENFORCED IN ACCORDANCE WITH THE LAWS OF TURKIYE.
			</Text>
			<Text>
				IN THE EVENT OF A DISPUTE ARISING BETWEEN THE PARTIES REGARDING THE
				INTERPRETATION, EXECUTION OR TERMINATION OF THESE TERMS, THE PARTIES
				SHALL ENDEAVOR TO RESOLVE SUCH ISSUE THROUGH AMICABLE MEANS.
				NOTWITHSTANDING ANYTHING TO THE CONTRARY PROVIDED HEREIN, THE COURT OF
				APPROPRIATE JURISDICTION SHALL BE THE VENUE FOR ANY FORMAL DISPUTES
				BETWEEN USER AND NIGHT WATCH.
			</Text>
		</Flex>
	);
}
